import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { readFile } from "fs/promises";
import { join } from "path";
import { existsSync } from "fs";

export async function GET(
    request: NextRequest,
    { params }: { params: Promise<{ id: string }> }
) {
    try {
        const { id } = await params;

        // Fetch submission from DB
        const submission = await prisma.submission.findUnique({
            where: { id },
        });

        if (!submission) {
            return NextResponse.json(
                { error: "Submission not found" },
                { status: 404 }
            );
        }

        const safeStudentName = submission.fullName.replace(/[^a-z0-9]/gi, "_");
        const safeSchoolName = submission.schoolName.replace(/[^a-z0-9]/gi, "_");

        if (submission.filePath) {
            // Serve uploaded file with automatic naming
            const filename = submission.filePath.split("/").pop();
            const ext = filename?.split(".").pop() || "docx";
            const downloadName = `${safeStudentName}-${safeSchoolName}.${ext}`;
            const filePath = join(process.cwd(), "public", "uploads", filename!);

            if (!existsSync(filePath)) {
                return NextResponse.json(
                    { error: "File not found" },
                    { status: 404 }
                );
            }

            const fileBuffer = await readFile(filePath);
            const contentType = ext === "pdf"
                ? "application/pdf"
                : "application/vnd.openxmlformats-officedocument.wordprocessingml.document";

            return new NextResponse(fileBuffer, {
                headers: {
                    "Content-Type": contentType,
                    "Content-Disposition": `attachment; filename="${downloadName}"`,
                    "Cache-Control": "no-cache",
                },
            });
        } else if (submission.content) {
            // Generate professional document from text content
            const downloadName = `${safeStudentName}-${safeSchoolName}.docx`;

            // Professional HTML with Word metadata (MIME type will handle it as DOCX)
            const htmlContent = `
                <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
                <head>
                    <meta charset="utf-8">
                    <title>${submission.essayTitle}</title>
                    <style>
                        body { font-family: 'Times New Roman', serif; line-height: 1.6; color: #333; padding: 40px; }
                        .header { border-bottom: 2px solid #008080; margin-bottom: 30px; padding-bottom: 10px; }
                        .info-grid { display: grid; grid-template-columns: 100px 1fr; gap: 10px; margin-bottom: 40px; }
                        .label { font-weight: bold; color: #666; }
                        h1 { color: #008080; text-align: center; margin-bottom: 30px; }
                        .content { white-space: pre-wrap; margin-top: 20px; }
                        .footer { margin-top: 50px; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <h1>${submission.essayTitle}</h1>
                    </div>
                    
                    <div class="info-grid">
                        <div class="label">Student:</div> <div>${submission.fullName}</div>
                        <div class="label">School:</div> <div>${submission.schoolName}</div>
                        <div class="label">Grade:</div> <div>${submission.gradeLevel}</div>
                        <div class="label">Date:</div> <div>${new Date(submission.createdAt).toLocaleDateString()}</div>
                    </div>

                    <div class="content">
                        ${submission.content}
                    </div>

                    <div class="footer">
                        Generated by The Bridge Essay Competition Portal
                    </div>
                </body>
                </html>
            `;

            return new NextResponse(htmlContent, {
                headers: {
                    "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    "Content-Disposition": `attachment; filename="${downloadName}"`,
                    "Cache-Control": "no-cache",
                },
            });
        } else {
            return NextResponse.json(
                { error: "No content available for download" },
                { status: 400 }
            );
        }
    } catch (error) {
        console.error("Download error:", error);
        return NextResponse.json(
            { error: "Failed to download file" },
            { status: 500 }
        );
    }
}
